<a href="https://colab.research.google.com/github/Bailipativaralakshmi-stack/nasscomworkshop/blob/main/Copy_of_NumPy_Practice_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Exercises

Solve each question in the code cell below it. Do not just re-run the lab examples — use **different numbers/data** than what was shown in class so you are actually writing the logic yourself.

Run each cell with **Shift + Enter** and check that your output makes sense before moving to the next question.

### Q1. Creating a 1-D array
Create a 1-D NumPy array containing 6 numbers of your choice. Print the array and print its type using `type()`.

In [ ]:
# Write your code here
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


### Q2. Creating a 2-D array
Create a 2-D NumPy array with 3 rows and 2 columns (any numbers). Print the array.

In [ ]:
# Write your code here
import numpy as np
arr2 = np.array([[1,2],[3,4],[5,6]])
print(arr)

[[1 2]
 [3 4]
 [5 6]]


### Q3. Creating a 3-D array
Create a 3-D NumPy array made up of two 2x3 matrices (2 blocks, each with 2 rows and 3 columns). Print the array.

In [ ]:
# Write your code here
import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,21]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 21]]]


### Q4. Checking the number of dimensions
Using the three arrays you created in Q1, Q2, and Q3, print the number of dimensions of each using the `.ndim` attribute.

In [ ]:
# Write your code here
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2],[3,4],[5,6]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,21]]])
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


### Q5. Accessing elements with indexing
Create a 2-D array with 2 rows and 5 columns of your own numbers.
1. Print the 3rd element of the 1st row using positive indexing.
2. Print the last element of the 2nd row using **negative** indexing.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,2])
print(arr[1,-1])



3
10


### Q6. Accessing elements in a 3-D array
Using the 3-D array you created in Q3, access and print one specific element using three indices, e.g. `arr[block, row, col]`.

In [ ]:
# Write your code here
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,21]]])
print(arr3[0,1,2])

6


### Q7. Checking data type
Create one NumPy array of integers and one NumPy array that contains at least one decimal number. Print the `.dtype` of each and explain in a comment why they are different.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = np.array([1.2,6,7,9])#single value of float value makes the array as float array
print(arr.dtype)
print(arr1.dtype)


int64
float64


### Q8. Copy vs View
Create a 1-D array. Make a **copy** of it using `.copy()` and a **view** of it using `.view()`. Change the first element of the original array, then print the original array, the copy, and the view. In a comment, explain what you observe and why.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([1,2,3,4,5])
arr1 = np.array([1,5,6,7,8])
x = arr.copy()#first array is reflected
y = arr1.view()#both arrays are reflected
arr[0]= 12
arr1[0]=13
print(arr)
print(arr1)
print(x)
print(y)


[12  2  3  4  5]
[13  5  6  7  8]
[1 2 3 4 5]
[13  5  6  7  8]


### Q9. Shape of an array
1. Create a 2-D array with 3 rows and 4 columns and print its `.shape`.
2. Create a 1-D array of 4 numbers with `ndmin=5` and print both the array and its shape.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([[1,3,4,5],[11,22,33,44],[23,11,45,67]])
arr1 = np.array([12,21,32,43],ndmin=5)
print(arr.shape)
print(arr1.shape)


(3, 4)
(1, 1, 1, 1, 4)


### Q10. Reshaping arrays
Create a 1-D array with 15 elements. Reshape it into a 2-D array with 3 rows and 5 columns using `.reshape()`. Print the result.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr1=arr.reshape(3,5)
print(arr1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### Q11. Linear algebra with NumPy
Solve the following system of equations using `np.linalg.solve()`:

2x + y = 11

x + 3y = 18

Print the values of x and y.

In [ ]:
# Write your code here
import numpy as np
a = np.array([[2,1],[1,3]])
b = np.array([11,18])
x = np.linalg.solve(a,b)
print(x)

[3. 5.]


### Q12. arange, zeros, and ones
1. Use `np.zeros()` to create a 4x2 array of zeros.
2. Use `np.ones()` to create a 3x3 array of ones.
3. Use `np.arange()` to create an array of numbers from 5 to 30 with a step of 5.

Print all three.

In [ ]:
# Write your code here
import numpy as np
arr = np.zeros((4,2))
arr1 = np.ones((3,3))
arr2 = np.arange(5,30,5)
print(arr)
print(arr1)
print(arr2)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 5 10 15 20 25]


### Q13. Why NumPy is faster than plain Python
Create two Python lists of 500,000 numbers each. Time how long it takes to add them element-by-element using a Python loop (or list comprehension). Then convert both lists to NumPy arrays and time how long it takes to add them using `+`. Print both times and, in a comment, state which was faster and roughly by how much.

In [ ]:
# Write your code here
import numpy as np
import time
a = list(range(500000))
b = list(range(500000))
start = time.time()
c = [a[i] + b[i] for i in range(len(a))]
python_time = time.time() - start
a_np = np.array(a)
b_np = np.array(b)
start1 = time.time()
c = a_np + b_np
numpy_time = time.time() - start1
print("python time:",python_time)
print("numpy time:",numpy_time)
print("numpy time is faster")


python time: 0.11544322967529297
numpy time: 0.01401519775390625
numpy time is faster


### Q14. Vectors vs matrices
Create a 1-D NumPy array representing a single customer's features: `[height_cm, weight_kg, age]` (make up your own values). Then create a 2-D NumPy array representing 4 different customers with the same 3 features each. Print the `.shape` and `.ndim` of both arrays.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([150,67,25])
arr1 = np.array([[155,58,24],[156,57,25],[158,60,44],[156,66,45]])
print(arr.shape)
print(arr.ndim)
print(arr1.shape)
print(arr1.ndim)




(3,)
1
(4, 3)
2


### Q15. Indexing and slicing to build X and y
Create a 2-D array with 6 rows and 3 columns, where the last column is a target label (0 or 1) and the first two columns are features (make up your own numbers).
1. Print the first 3 rows only.
2. Print only the first column, for all rows.
3. Split the array into `X` (all columns except the last) and `y` (only the last column), and print both.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([[1,2,0],[4,5,1],[7,8,0],[10,11,1],[13,14,0],[16,17,1]])
print(arr[:3])
print(arr[:,0])
x=arr[:,:-1]
y=arr[:,-1]
print(x)
print(y)


[[1 2 0]
 [4 5 1]
 [7 8 0]]
[ 1  4  7 10 13 16]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]
 [16 17]]
[0 1 0 1 0 1]


### Q16. Vectorized operations and boolean masking
Create a 1-D NumPy array of 8 exam scores (0-100) of your choice. Without using any loop:
1. Add 5 bonus marks to every score and print the result.
2. Print a boolean array showing which scores are 50 or above.
3. Print only the scores that are 50 or above using boolean masking.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([88,34,55,66,77,90,34,56])
bonus = arr+5 #add 5 to every element
print(bonus)
mask = arr>=50 #if element is greater than 50
print(mask)
print(arr[mask])


[93 39 60 71 82 95 39 61]
[ True False  True  True  True  True False  True]
[88 55 66 77 90 56]
